[package]
name = "sim"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]
links = "osm"
build = "build.rs"

[dependencies]
sfml = "0.14.0"
error-chain = "0.11.0"
libc = "0.2.34"
reqwest = "0.8.1"
c_str_macro = "1.0.2"
